/*

Problem 389. Find the Difference

    - You are given two strings s and t.

		- String t is generated by random shuffling string s and then add one more letter at a random position.

		- Return the letter that was added to t.
    
    - Example:

			Input: s = "abcd", t = "abcde"
			Output: "e"
			Explanation: 'e' is the letter that was added.

			Input: s = "", t = "y"
			Output: "y"

		- Constraints:
			0 <= s.length <= 1000
			t.length == s.length + 1
			s and t consist of lowercase English letters.

*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */

var findTheDifference = function(s, t) {
	for (let index = 0; index < s.length; index++) {
		if(t.indexOf(s[index]) !== -1) t= t.replace(s[index], '');
	}
	return t;
};